name: Magma
favicon: null
layout_spectrum: 0.9666511146351695
typography_spectrum: 0.6964913979172707
title: 'Video production & Marketing'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.625
  lightness: 0.27105444739572704
  saturation: 0.7994775683619082
  rhythmicContrast: 0.7724928525276482
purpose: []
